#!/usr/bin/python3
import requests
import sys
import os


class spa:
	def init():
		os.system("cp ./spa /usr/bin/spa")

	def spa(action, package):
		if action == "install":
			if input(f"Are you sure you want to {action} package {package}? [y/n]").lower() == "y":
				print("Downloading...")
				pkg = requests.get(f"https://spa.ssniper1.ml/{package}.tar.xz")
				print("Downloading done! Now writing...")
				#os.system(f"touch ./{package}.tar.xz")
				pkgfile = open(f"./{package}.tar.xz", "wb")
				pkgfile.write(pkg.content)
				pkgfile.close()
				print("Installing...")
				os.system(f"tar xf {package}.tar.xz && mv {package} /usr/bin/{package} && rm -rf {package}.tar.xz")
				print(f"Done! You can launch newly installed program by entering {package}")

		elif action == "remove" or action == "delete":
			if input(f"Are you sure you want to delete package {package}? [y/N]").lower() == "y":
				if package == "spa":
					if input("This is potentially unneeded because you want to delete spa package itself! Are you sure 100%? [y/N]").lower() == "y":
						os.system(f"rm /usr/bin/{package}")
					os.system(f"rm -rf /usr/bin/{package}")

		elif action == "about":
			desc = requests.get(f"https://spa.ssniper1.ml/desc/{package}.desc")
			print(desc.content.decode())

		elif action == "init":
			spa.init()


def checkArgs():
	if len(sys.argv) < 3:
		print("You forgot to specify something!")
	else:
		spa.spa(sys.argv[1], sys.argv[2])


if __name__ == "__main__":
	checkArgs()
